### ISSUE TITLE
Using breadcrumbs in the app.component.html and set breadcrumbs text in the internal module routing file

### ISSUE THREAD

**Issue by farzanehp** [exalif/angular-libs#33]
Hi, How can I use breadcrumbs directive in the app.component.html and set the breadcrumbs text in the internal module routing file, such as this 
``` 
app.component.html
...
<lib-breadcrumbs></lib-breadcrumbs>
<router-outlet></router-outlet>
...
```
```
business-routing.module.ts
...
const routes: Routes = [
  {
    path: 'businesses',
    children: [
      { path: '', redirectTo: 'list', pathMatch: 'full' },
      { path: 'list', component: BusinessCategoriesListComponent, data: { breadcrumbs: 'Owner and their businesses' } }
    ]
  }
];
...
```

Also, I have been imported the BreadcrumbsModule in the business.module.ts and app.module.ts 
Is it possible to use the breadcrumbs with this schema? What do I do for this goal?

**Comment by blackholegalaxy** [comment]
As stated in the readme here: https://github.com/exalif/angular-libs/tree/master/projects/ngx-breadcrumbs

You can use `<lib-breadcrumbs>` component where you want in your app. It's also optional and you are not required to use the component from the library.

You can define text breadcrumbs using data in your `list` route definition:
```typescript
data: {
  breadcrumbs: true,
  text: 'Your custom text here'
},
```

Your approach seems valid. I don't exactly get what is your problem here. Do you encounter any error?

**Comment by farzanehp** [comment]
@blackholegalaxy Hi 
Thanks for your response.
Must I use the breadcrumbs under the businesses path components in this example?
I have these components in the businesses module : 
businesses-list
business-overview
business-add 
....
I want to use the breadcrumbs in the app-component to display it in the all of modules components

**Comment by blackholegalaxy** [comment]
You can use breadcrumbs anywhere on the app.

**Comment by blackholegalaxy** [comment]
I will now close this issue. Feel free to open a new one if you encounter any problem!
